[2021-03-22 21:09:46,557] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.UploadLabledData 2021-03-23T04:08:56.640659+00:00 [queued]>
[2021-03-22 21:09:46,564] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.UploadLabledData 2021-03-23T04:08:56.640659+00:00 [queued]>
[2021-03-22 21:09:46,564] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-22 21:09:46,564] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-22 21:09:46,564] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-22 21:09:46,570] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): UploadLabledData> on 2021-03-23T04:08:56.640659+00:00
[2021-03-22 21:09:46,572] {standard_task_runner.py:52} INFO - Started process 28446 to run task
[2021-03-22 21:09:46,579] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EDGAR-Annotation-Pipeline', 'UploadLabledData', '2021-03-23T04:08:56.640659+00:00', '--job-id', '42', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/edgar_annotation.py', '--cfg-path', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpdm3mkaek', '--error-file', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmp_cvbuq7x']
[2021-03-22 21:09:46,580] {standard_task_runner.py:77} INFO - Job 42: Subtask UploadLabledData
[2021-03-22 21:09:46,612] {logging_mixin.py:104} INFO - Running <TaskInstance: EDGAR-Annotation-Pipeline.UploadLabledData 2021-03-23T04:08:56.640659+00:00 [running]> on host prathyushas-mbp.home
[2021-03-22 21:09:46,635] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EDGAR-Annotation-Pipeline
AIRFLOW_CTX_TASK_ID=UploadLabledData
AIRFLOW_CTX_EXECUTION_DATE=2021-03-23T04:08:56.640659+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-23T04:08:56.640659+00:00
[2021-03-22 21:09:46,674] {credentials.py:1222} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2021-03-22 21:09:48,005] {logging_mixin.py:104} INFO - annotation file uploaded
[2021-03-22 21:09:48,008] {python.py:118} INFO - Done. Returned value was: None
[2021-03-22 21:09:48,012] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=EDGAR-Annotation-Pipeline, task_id=UploadLabledData, execution_date=20210323T040856, start_date=20210323T040946, end_date=20210323T040948
[2021-03-22 21:09:48,026] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-22 21:09:48,057] {local_task_job.py:146} INFO - Task exited with return code 0
