[2021-03-22 19:53:22,839] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.UploadLabledData 2021-03-23T02:52:52.673866+00:00 [queued]>
[2021-03-22 19:53:22,847] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.UploadLabledData 2021-03-23T02:52:52.673866+00:00 [queued]>
[2021-03-22 19:53:22,847] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-22 19:53:22,847] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-22 19:53:22,848] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-22 19:53:22,855] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): UploadLabledData> on 2021-03-23T02:52:52.673866+00:00
[2021-03-22 19:53:22,857] {standard_task_runner.py:52} INFO - Started process 23831 to run task
[2021-03-22 19:53:22,865] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EDGAR-Annotation-Pipeline', 'UploadLabledData', '2021-03-23T02:52:52.673866+00:00', '--job-id', '15', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/edgar_annotation.py', '--cfg-path', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmp56mj_eoi', '--error-file', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpeeu3w2jz']
[2021-03-22 19:53:22,866] {standard_task_runner.py:77} INFO - Job 15: Subtask UploadLabledData
[2021-03-22 19:53:22,897] {logging_mixin.py:104} INFO - Running <TaskInstance: EDGAR-Annotation-Pipeline.UploadLabledData 2021-03-23T02:52:52.673866+00:00 [running]> on host prathyushas-mbp.home
[2021-03-22 19:53:22,920] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EDGAR-Annotation-Pipeline
AIRFLOW_CTX_TASK_ID=UploadLabledData
AIRFLOW_CTX_EXECUTION_DATE=2021-03-23T02:52:52.673866+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-23T02:52:52.673866+00:00
[2021-03-22 19:53:22,961] {credentials.py:1222} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2021-03-22 19:53:23,875] {logging_mixin.py:104} INFO - annotation file uploaded
[2021-03-22 19:53:23,878] {python.py:118} INFO - Done. Returned value was: None
[2021-03-22 19:53:23,888] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=EDGAR-Annotation-Pipeline, task_id=UploadLabledData, execution_date=20210323T025252, start_date=20210323T025322, end_date=20210323T025323
[2021-03-22 19:53:23,906] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-22 19:53:23,944] {local_task_job.py:146} INFO - Task exited with return code 0
