[2021-03-22 19:43:24,788] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.preprocess 2021-03-23T02:43:09.151483+00:00 [queued]>
[2021-03-22 19:43:24,793] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.preprocess 2021-03-23T02:43:09.151483+00:00 [queued]>
[2021-03-22 19:43:24,793] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-22 19:43:24,793] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-22 19:43:24,793] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-22 19:43:24,799] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): preprocess> on 2021-03-23T02:43:09.151483+00:00
[2021-03-22 19:43:24,802] {standard_task_runner.py:52} INFO - Started process 23294 to run task
[2021-03-22 19:43:24,810] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EDGAR-Annotation-Pipeline', 'preprocess', '2021-03-23T02:43:09.151483+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/edgar_annotation.py', '--cfg-path', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmps4nx147x', '--error-file', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpcq92vo02']
[2021-03-22 19:43:24,812] {standard_task_runner.py:77} INFO - Job 9: Subtask preprocess
[2021-03-22 19:43:24,842] {logging_mixin.py:104} INFO - Running <TaskInstance: EDGAR-Annotation-Pipeline.preprocess 2021-03-23T02:43:09.151483+00:00 [running]> on host prathyushas-mbp.home
[2021-03-22 19:43:24,862] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EDGAR-Annotation-Pipeline
AIRFLOW_CTX_TASK_ID=preprocess
AIRFLOW_CTX_EXECUTION_DATE=2021-03-23T02:43:09.151483+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-23T02:43:09.151483+00:00
[2021-03-22 19:43:25,226] {python.py:118} INFO - Done. Returned value was:                                                  Text company
0   Welcome everybody. Thank you for joining us to...      PD
1   So were ready to get started. Im going to turn...      PD
2   Great. Thank you. Good afternoon and thank you...      PD
3   Statements made on todays call will include fo...      PD
4   During todays call we will discuss nonGAAP fin...      PD
..                                                ...     ...
65  Having said that if  should Canacol or any oth...   CNNEF
66  We have one last question from James Branch ph...   CNNEF
67  Yes thank you James. Yes as we continue to add...   CNNEF
68  Thank you Charle. We dont have any more questi...   CNNEF
69  The conference is now concluded. Thank you for...   CNNEF

[5238 rows x 2 columns]
[2021-03-22 19:43:25,237] {xcom.py:237} ERROR - Could not serialize the XCom value into JSON. If you are using pickles instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2021-03-22 19:43:25,237] {taskinstance.py:1455} ERROR - Object of type DataFrame is not JSON serializable
Traceback (most recent call last):
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1318, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1893, in xcom_push
    XCom.set(
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/utils/session.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/models/xcom.py", line 88, in set
    value = XCom.serialize_value(value)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/models/xcom.py", line 235, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/Users/prathyusha/opt/anaconda3/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Users/prathyusha/opt/anaconda3/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/prathyusha/opt/anaconda3/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/prathyusha/opt/anaconda3/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2021-03-22 19:43:25,246] {taskinstance.py:1496} INFO - Marking task as FAILED. dag_id=EDGAR-Annotation-Pipeline, task_id=preprocess, execution_date=20210323T024309, start_date=20210323T024324, end_date=20210323T024325
[2021-03-22 19:43:25,276] {local_task_job.py:146} INFO - Task exited with return code 1
